### ISSUE TITLE
Default content-type is "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by pfirsich** [LPGhatguy/luajit-request#10]
If you just pass a string as data to the .send method, it will be included in the message body as is, but the content-type of the request will be, as stated in the title, "application/x-www-form-urlencoded". This is not just a pitfall that might confuse the webservers serving the url, but is plainly incorrect most of the time. This default behaviour is inherent to curl, as google searches show, but assuming we get bytes of some random content type, the best guess is "application/octet-stream" (RFC2046): "The "octet-stream" subtype is used to indicate that a body contains arbitrary binary data"

**Comment by LPGhatguy** [comment]
I agree, this was an oversight.
