### ISSUE TITLE
Windows can only POST/GET

### ISSUE THREAD

**Issue by MrcSnm** [LPGhatguy/luajit-request#14]
Worth mentioning that, on Windows, cURL can only execute POST and GET, the current workaround is:
Adding the following request header
Key: X-HTTP-Method-Override Value: Target method (PUT, PATCH, DELETE)

Remembering that I made a Mega Async REST Wrap, it do uses luajit-request, but only on Windows, as I would need to include another binary for Linux, and it is currently supporting:
Android, Windows, Linux and Web(Love.js), everything with little to no adaptation, (only a .js file when using on Web)
[**REST-Love**](https://github.com/MrcSnm/REST-love)

**Comment by pfirsich** [comment]
I don't know if anything changed but a bit over a year ago I used luajit-request in a game of mine that also used PUT, DELETE and PATCH and all of those definitely worked, just by passing `{method = "PUT"}` for `args` (second argument to `send`). I am now using Linux, so I can't try it out easily.

Could you make a minimal example that shows the faulty behaviour? (You could send a request to `https://httpbin.org/anything` and print it, which will also return the method used for the request)

**Comment by MrcSnm** [comment]
I've just tested right now again and noticed that there was a typo where I passed methd instead of method, and I believe that as it received the data parameter correctly it just transformed into a POST method and by appending those headers I could make it work, sorry for the mismatch
