### ISSUE TITLE
Windows distribution problems with löve - cannot load module libcurl.

### ISSUE THREAD

**Issue by pfirsich** [LPGhatguy/luajit-request#8]
After downloading the libcurl.dll (with SSL support) that is linked in the readme and putting it next to my love.exe, the library works right away for me. But for three out of three friends that I asked to try it too, everyone gets the error:

> msg = string: "luajit-request/luajit-curl.lua:28: cannot load module 'libcurl': Das angegebene Modul wurde nicht gefunden.\13\

I made sure that love.exe is 32-Bit, just as libcurl.dll. Dependency walker tells me that libcurl.dll has three dependencies: zlib1.dll, ssleay32.dll and libeay32.dll, which I hoped would be included in libcurl.dll. But just to make sure, I searched them from other places on my computer and put them next to the exe too. Then I got a "missing ordinal 4445 in dll" error instead, most probably because their versions do not match, but maybe that's a lead? I also tried setting PATH and LUA_CPATH to the directory of the .dll and I passed a full absolute path to the dll to ffi.load instead, but I still get the error I mentioned in the start of this issue.

I would guess that most people will have trouble using the library, because everyone else seems to be having the problem.

**Comment by pfirsich** [comment]
It turns out the only working version of libcurl.dll I have found so far that works on all computers tested is the one linked here: https://curl.haxx.se/download.html
(Win64 Generic - Win64  x86_64  CAB | 7.54.1 | binary | SSL - link: https://skanthak.homepage.t-online.de/download/curl-7.54.1.cab) I don't what's going on with the other ones, but maybe you can update the link in the readme?

**Comment by LPGhatguy** [comment]
Good catch, just like your other issues!

I have this fuzzy memory that the haxxe.se links didn't have Windows binaries whenever I wrote that README, or at least not with SSL support built in?

I'll update the README!

**Comment by LPGhatguy** [comment]
README has been updated to point to those binaries instead, thank you!

**Comment by pfirsich** [comment]
It's a pleasure! I'm really thankful you made this and if I can contribute only by complaining, I'll gladly take it :D

**Comment by david-sharer** [comment]
Data point for future visitors:

I tried getting the latest binaries out of haxx.se, but they did not work for me. I just got a lot of the following. 
![image](https://user-images.githubusercontent.com/26589071/74580222-87105e00-4f56-11ea-92e3-11b107ed4c5b.png)

When I used the old one linked above, it worked fine.
> (Win64 Generic - Win64 x86_64 CAB | 7.54.1 | binary | SSL - link: https://skanthak.homepage.t-online.de/download/curl-7.54.1.cab)

(I'm using Love2D 11.3.0)
